ALTER TABLE users ADD COLUMN email VARCHAR(120);
ALTER TABLE users ADD COLUMN full_name VARCHAR(120);
ALTER TABLE users ADD COLUMN phone VARCHAR(40);
ALTER TABLE users ADD COLUMN address VARCHAR(255);
ALTER TABLE users ADD COLUMN notify_orders BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE users ADD COLUMN notify_stock BOOLEAN DEFAULT TRUE NOT NULL;

ALTER TABLE medications ADD COLUMN description VARCHAR(1000);
ALTER TABLE medications ADD COLUMN image_url VARCHAR(500);

CREATE TABLE support_tickets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    subject VARCHAR(160) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    category VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES users(id)
);
